### ISSUE TITLE
Akkustand 

### ISSUE THREAD

**Issue by Geri-G93** [ice987987/ioBroker.spritmonitor#74]
### Feature or idea description

Hallo
Wollte mal nachhaken ob die Möglichkeit besteht noch den Prozentsatz einzubinden

Ansonsten top zufrieden mit dem Adapter 😊

Mfg

### Version of "spritmonitor"-adapter

0.0.1

**Comment by ice987987** [comment]
welcher Prozentsatz fehlt? Dieser ist z.B im `spritmonitor.0.xyz.fuelings.raw` enthalten.

**Comment by Geri-G93** [comment]
akkustand
kann man bei Add mit übermitteln, scheint dazugekommen zu sein
hab das mir selber eingebastelt mittlerweile 
https://github.com/FundF/Spritmonitor-API-sample-code/blob/main/Add_Fuel_Entry/add_fuel_entry.py
Line 51+59

**Comment by ice987987** [comment]
please check 0.0.3-beta.1
